### ISSUE TITLE
LoadError cannot load such file colorize

### ISSUE THREAD

**Issue by hegazy** [cesarferreira/dryrun#100]
I got this error when trying to run `dryrun https://github.com/cesarferreira/android-helloworld`
```
/Library/Ruby/Gems/2.0.0/gems/dryrun-1.0.0/lib/dryrun.rb:1:in `require': cannot load such file -- colorize (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-1.0.0/lib/dryrun.rb:1:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-1.0.0/bin/dryrun:4:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-1.0.0/bin/dryrun:4:in `<top (required)>'
	from /usr/local/bin/dryrun:23:in `load'
	from /usr/local/bin/dryrun:23:in `<main>'
```

**Comment by cesarferreira** [comment]
Just checked the gemspec
https://github.com/cesarferreira/dryrun/blob/master/dryrun.gemspec

` s.add_dependency 'colorize', '~> 0.7'`

and it's there, maybe this is some issue because you are using a really old version of ruby?
2.0.0 is like 2 years old now

**Comment by hegazy** [comment]
@cesarferreira Updating my ruby version to 2.4.2 fixed it. Thanks 👍

**Comment by hegazy** [comment]
And it's back! What's up with this one!
```
/Users/ahmedhegazy/.rvm/gems/ruby-2.4.2/gems/dryrun-1.1.0/lib/dryrun.rb:1:in `require': cannot load such file -- colorize (LoadError)
	from /Users/ahmedhegazy/.rvm/gems/ruby-2.4.2/gems/dryrun-1.1.0/lib/dryrun.rb:1:in `<top (required)>'
	from /Users/ahmedhegazy/.rvm/gems/ruby-2.4.2/gems/dryrun-1.1.0/bin/dryrun:4:in `require'
	from /Users/ahmedhegazy/.rvm/gems/ruby-2.4.2/gems/dryrun-1.1.0/bin/dryrun:4:in `<top (required)>'
	from /Users/ahmedhegazy/.rvm/gems/ruby-2.4.2/bin/dryrun:23:in `load'
	from /Users/ahmedhegazy/.rvm/gems/ruby-2.4.2/bin/dryrun:23:in `<main>'
	from /Users/ahmedhegazy/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ahmedhegazy/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

The problem is that the colorize is already installed with version "0.8.1"!

**Comment by cesarferreira** [comment]
what's up with ruby man :P 

do you know a way to tell him to use this version instead of me having to upgrade the version if someone installs it on their side?

**Comment by hegazy** [comment]
And it's working again after updating! it should be working with your configuration!
