### ISSUE TITLE
Cannot start sample module from repository

### ISSUE THREAD

**Issue by ghostbuster91** [cesarferreira/dryrun#111]
```
 dryrun git@github.com:chrisbanes/PhotoView.git -m sample

Searching for devices...
Picked 025c30c316980d07
Found project in /tmp/dryrun/chrisbanes/PhotoView...
HEAD is now at 86d7c19 Merge pull request #570 from SimonRolin/patch-1
Fetching origin
Already on 'master'
Your branch is up-to-date with 'origin/master'.
From github.com:chrisbanes/PhotoView
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Using custom module: sample
/home/kasper/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dryrun-1.1.2/lib/dryrun/install_application_command.rb:29:in `launcheable_activity': undefined method `gsub' for false:FalseClass (NoMethodError)
	from /home/kasper/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dryrun-1.1.2/lib/dryrun/install_application_command.rb:25:in `get_execution_command_line'
	from /home/kasper/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dryrun-1.1.2/lib/dryrun/install_application_command.rb:8:in `run'
	from /home/kasper/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dryrun-1.1.2/lib/dryrun/android_project.rb:104:in `execute_command'
	from /home/kasper/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dryrun-1.1.2/lib/dryrun.rb:208:in `call'
	from /home/kasper/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dryrun-1.1.2/bin/dryrun:6:in `<top (required)>'
	from /home/kasper/.rbenv/versions/2.3.1/bin/dryrun:23:in `load'
	from /home/kasper/.rbenv/versions/2.3.1/bin/dryrun:23:in `<main>'
```

Am I doing something wrong?

**Comment by ghostbuster91** [comment]
After almost an hour I found the problem.
The modules in the mentioned project in, which are defined in `settings.gradle` file, are specified like this:
```
include 'photoview'
include 'sample'
```
So they both miss `:` character. But it looks like this is also a valid syntax for gradle so it should be supported.

**Comment by cesarferreira** [comment]
> dryrun git@github.com:chrisbanes/PhotoView.git

This should open the sample anyway, did you change something towards this issue?

**Comment by ghostbuster91** [comment]
I tried and it failed:
```
dryrun git@github.com:chrisbanes/PhotoView.git
Searching for devices...
No devices attached, but I'll run anyway
Found project in /tmp/dryrun/chrisbanes/PhotoView...
HEAD is now at 86d7c19 Merge pull request #570 from SimonRolin/patch-1
Fetching origin
Already on 'master'
Your branch is up-to-date with 'origin/master'.
From github.com:chrisbanes/PhotoView
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Couldn't open or there isnt any sample project, sorry!
```

**Comment by cesarferreira** [comment]
yep, it used to work before your other pull request, that's why I'm asking, did you change the behaviour?

**Comment by ghostbuster91** [comment]
It looks that I did, but it wasn't my intention :(

**Comment by cesarferreira** [comment]
crap :D 

can you revert it please?

**Comment by ghostbuster91** [comment]
By reverting, you mean the behaviour, not the commit, yes? 
I found the difference. In the past you were scanning the directory to find first module which has a valid manifest. 
I will do a PR.

**Comment by cesarferreira** [comment]
Exactly, just the behaviour ;)

thanks man :)
