### ISSUE TITLE
Can't run JakeWharton's telecine app

### ISSUE THREAD

**Issue by Kisty** [cesarferreira/dryrun#128]
I can't run Jake Wharton's screen recording app: https://github.com/JakeWharton/Telecine.

When I specify the module `dryrun https://github.com/JakeWharton/Telecine -m telecine` it doesn't work:

```
HEAD is now at 0e4ee6a AGP 3.0b5
Fetching origin
Already on 'master'
Your branch is up to date with 'origin/master'.
From https://github.com/JakeWharton/Telecine
 * branch            master     -> FETCH_HEAD
Already up to date.
Using custom module: telecine
Couldn't open or there isnt any sample project, sorry!
```

When I do `dryrun https://github.com/JakeWharton/Telecine`, it fails with stacktrace:

```
Searching for devices...
Picked emulator-5554
Found project in C:/Users/MyUser/AppData/Local/Temp/dryrun/JakeWharton/Telecine...
HEAD is now at 0e4ee6a AGP 3.0b5
Fetching origin
Already on 'master'
Your branch is up to date with 'origin/master'.
From https://github.com/JakeWharton/Telecine
 * branch            master     -> FETCH_HEAD
Already up to date.
C:/Users/MyUser/AppData/Local/Temp/dryrun/JakeWharton/Telecine/telecine-project
C:/Users/MyUser/scoop/apps/ruby/current/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
        from C:/Users/MyUser/scoop/apps/ruby/current/lib/ruby/2.3.0/find.rb:43:in `collect!'
        from C:/Users/MyUser/scoop/apps/ruby/current/lib/ruby/2.3.0/find.rb:43:in `find'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/gems/dryrun-1.1.6/lib/dryrun/android_project.rb:153:in `get_manifest'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/gems/dryrun-1.1.6/lib/dryrun/android_project.rb:135:in `parse_manifest'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/gems/dryrun-1.1.6/lib/dryrun/android_project.rb:120:in `block in sample_project'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/gems/dryrun-1.1.6/lib/dryrun/android_project.rb:117:in `each'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/gems/dryrun-1.1.6/lib/dryrun/android_project.rb:117:in `sample_project'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/gems/dryrun-1.1.6/lib/dryrun/android_project.rb:91:in `execute_command'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/gems/dryrun-1.1.6/lib/dryrun.rb:208:in `call'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/gems/dryrun-1.1.6/bin/dryrun:6:in `<top (required)>'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/bin/dryrun:22:in `load'
        from C:/Users/MyUser/scoop/apps/ruby/current/gems/bin/dryrun:22:in `<main>'
```

dryrun version: 1.1.6
Windows 10 64-bit

**Comment by cesarferreira** [comment]
Fixed here, let me know if you have any more issues https://github.com/cesarferreira/dryrun/releases/tag/1.2.0

**Comment by alashow** [comment]
I have a similar problem with material-components:
```ruby
> dryrun  https://github.com/material-components/material-components-android/ -m catalog
Searching for devices...
No devices attached, but I'll run anyway
Found project in /var/folders/_l/vn4l7vn95r37b80cx3c_82gc0000gn/T/dryrun/material-components/material-components-android...
HEAD is now at 889ff8a Updated TextInputLayout to support empty string as error message.
Fetching origin
Already on 'master'
Your branch is up to date with 'origin/master'.
From https://github.com/material-components/material-components-android
 * branch            master     -> FETCH_HEAD
Already up to date.
Using custom module: catalog
/var/folders/_l/vn4l7vn95r37b80cx3c_82gc0000gn/T/dryrun/material-components/material-components-android/catalog
Couldn't open or there isnt any sample project, sorry!
```

**Comment by MarioNoll** [comment]
Same issue for me with material-components, would be great if this could be fixed.
