### ISSUE TITLE
having issue with installing in the windows 10

### ISSUE THREAD

**Issue by jaydip430** [cesarferreira/dryrun#140]
C:\Users\jay95>gem install dryrun
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing dryrun:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rjb-1.6.4/ext
C:/Ruby27-x64/bin/ruby.exe -I C:/Ruby27-x64/lib/ruby/2.7.0 -r ./siteconf20211021-19364-1j9vjd4.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby27-x64/bin/$(RUBY_BASE_NAME)
extconf.rb:46:in `open': No such file or directory @ dir_initialize - C:\\Program Files\\Java\\jdk-14.0.1\\bin\\include (Errno::ENOENT)
        from extconf.rb:46:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rjb-1.6.4 for inspection.
Results logged to C:/Ruby27-x64/lib/ruby/gems/2.7.0/extensions/x64-mingw32/2.7.0/rjb-1.6.4/gem_make.out

**Comment by cesarferreira** [comment]
If it works on windows it's almost a coincidence, I haven't touched a windows machine in 7+ years
