### ISSUE TITLE
OpenTimeOut

### ISSUE THREAD

**Issue by LikeWather** [cesarferreira/dryrun#141]
Hello，
My computer is Mac OS，
The CPU is M1。
I can do it "dryrun -v"，when i do "dryrun https://github.com/cesarferreira/android-helloworld"。
The system gives a prompt。
---------------------------------------------------------------------------
dryrun https://github.com/cesarferreira/android-helloworld
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `initialize': execution expired (Net::OpenTimeout)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:736:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:35:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:46:in `open'
	from /Library/Ruby/Gems/2.6.0/gems/dryrun-1.3.2/lib/dryrun/dryrun_utils.rb:30:in `latest_version'
	from /Library/Ruby/Gems/2.6.0/gems/dryrun-1.3.2/lib/dryrun/dryrun_utils.rb:39:in `up_to_date'
	from /Library/Ruby/Gems/2.6.0/gems/dryrun-1.3.2/lib/dryrun.rb:89:in `outdated_verification'
	from /Library/Ruby/Gems/2.6.0/gems/dryrun-1.3.2/lib/dryrun.rb:18:in `initialize'
	from /Library/Ruby/Gems/2.6.0/gems/dryrun-1.3.2/bin/dryrun:6:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/dryrun-1.3.2/bin/dryrun:6:in `<top (required)>'
	from /usr/local/bin/dryrun:23:in `load'
	from /usr/local/bin/dryrun:23:in `<main>'

**Comment by cesarferreira** [comment]
I don't have the M1 yet, I'll take a look once I have it, meanwhile if you or anyone else with an M1 that can give a help it'd be appreciated!
