### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by jacoplane** [cesarferreira/dryrun#27]
So I'm getting this error:

```
> dryrun https://github.com/javiersantos/MaterialStyledDialogs
Cloning into 'C:/Users/jaapv/AppData/Local/Temp/dryrun/641ae71289933e1c2d077f65ecc7a8eab8975a6046a64363a1d0636bdbb34569'...
remote: Counting objects: 443, done.
remote: Compressing objects: 100% (3/3), done.
Receiving objects:  75% (333/443), 2.14 MiB | 1.36 MiB/s    440
Receiving objects: 100% (443/443), 3.48 MiB | 1.36 MiB/s, done.
Resolving deltas: 100% (168/168), done.
Checking connectivity... done.


======================================================

 Something went wrong while executing this:
  $ chmod +x gradlew

======================================================
```

Now I looked at your closed issues and it seems dryrun should run on Windows, but chmod doesn't work on Windows. Am I doing it wrong?

**Comment by cesarferreira** [comment]
Hey!
Never thought of that, I made it do the `chmod` because some developers push the gradlew without execution permissions.
It was not intended to work on windows but apparently some people say it works.
Just added a verification for windows users, can you please try it now? just update to the latest version `0.6.3`

Cheers

**Comment by jacoplane** [comment]
Thanks for looking into this! I'm getting this error now:

```
> dryrun https://github.com/javiersantos/MaterialStyledDialogs
Found project in C:/Users/jaapv/AppData/Local/Temp/dryrun/641ae71289933e1c2d077f65ecc7a8eab8975a6046a64363a1d0636bdbb34569...
HEAD is now at 6466cf4 Update README.md
Fetching origin
Already on 'master'
Your branch is up-to-date with 'origin/master'.
From https://github.com/javiersantos/MaterialStyledDialogs
 * branch            master     -> FETCH_HEAD
Already up-to-date.
C:/a_webdev/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:528:in `rename': Permission denied @ rb_file_s_rename - (C:/Users/jaapv/AppData/Local/Temp/extract20160425-13844-1w2y9ty, C:/Users/jaapv/AppData/Local/Temp/dryrun/641ae71289933e1c2d077f65ecc7a8eab8975a6046a64363a1d0636bdbb34569/app/build.gradle) (Errno::EACCES)
        from C:/a_webdev/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
        from C:/a_webdev/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
        from C:/a_webdev/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
        from C:/a_webdev/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
        from C:/a_webdev/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
        from C:/a_webdev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.6.3/lib/dryrun/android_project.rb:53:in `remove_application_id'
        from C:/a_webdev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.6.3/lib/dryrun/android_project.rb:95:in `install'
        from C:/a_webdev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.6.3/lib/dryrun.rb:103:in `call'
        from C:/a_webdev/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.6.3/bin/dryrun:5:in `<top (required)>'
        from C:/a_webdev/Ruby23-x64/bin/dryrun:23:in `load'
        from C:/a_webdev/Ruby23-x64/bin/dryrun:23:in `<main>'
```

**Comment by cesarferreira** [comment]
I currently don't own any windows machine so I have no way to debug this issue, if anyone would be kind enough to help It'd be great.

Sorry @jacoplane !
