### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by alighters** [cesarferreira/dryrun#4]
When I excuted "dryrun https://github.com/venmo/tooltip-view.git", I got the error below:

Cloning into '/var/folders/h8/wtp4421j0874f1smkwc79pg80000gn/T/dryrun/venmo/tooltip-view'...
remote: Counting objects: 168, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 168 (delta 32), reused 0 (delta 0), pack-reused 80
Receiving objects: 100% (168/168), 169.57 KiB | 5.00 KiB/s, done.
Resolving deltas: 100% (37/37), done.
Checking connectivity... done.
Failure
Downloading https://services.gradle.org/distributions/gradle-2.2-all.zip

Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
    at org.gradle.wrapper.Install.createDist(Install.java:47)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:980)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2661)
    at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2583)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1769)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
    at org.gradle.wrapper.Download.download(Download.java:45)
    at org.gradle.wrapper.Install$1.call(Install.java:60)
    at org.gradle.wrapper.Install$1.call(Install.java:47)
    at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
    ... 3 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
    at sun.security.ssl.InputRecord.read(InputRecord.java:505)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961)
    ... 18 more
Installing com.venmo.view.tooltip.example...
executing: adb shell am start -n "com.venmo.view.tooltip.example/com.venmo.view.tooltip.example.TooltipActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.venmo.view.tooltip.example/.TooltipActivity }
Error type 3
Error: Activity class {com.venmo.view.tooltip.example/com.venmo.view.tooltip.example.TooltipActivity} does not exist.

> If you want to remove the app you just installed, execute:
> adb uninstall com.venmo.view.tooltip.example

**Comment by cesarferreira** [comment]
Hey mate, 
It looks like you can't download the gradle-2.2

> Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

maybe your firewall is blocking it?

type:

> cd /var/folders/h8/wtp4421j0874f1smkwc79pg80000gn/T/dryrun/venmo/tooltip-view
> ./gradlew clean assemble

Tell me the output

**Comment by alighters** [comment]
I think it's the firewall problem. I change the vpn and it can download now. You did a great work, thanks a lot.

**Comment by cesarferreira** [comment]
Cool, great to hear that :+1: 
Thanks a bunch!
