### ISSUE TITLE
settings.gradle (Errno::ENOENT)

### ISSUE THREAD

**Issue by krokyze** [cesarferreira/dryrun#54]
Platform: Windows 10 64bit

Had this error with "dryrun https://github.com/krokyze/Let-s-Go-Out"

```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.9/lib/dryrun/android_project.rb:81:in `initialize': No such file or directory @ rb_sysopen - C:/Users/Krokyze/AppData/Local/Temp/dryrun/bb9c73d1599bc6822050cd0a32c1b3d27a854c277597c243eb9f44979d5f147b/settings.gradle (Errno::ENOENT)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.9/lib/dryrun/android_project.rb:81:in `open'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.9/lib/dryrun/android_project.rb:81:in `find_modules'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.9/lib/dryrun/android_project.rb:22:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.9/lib/dryrun.rb:194:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.9/lib/dryrun.rb:194:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.9/bin/dryrun:5:in `<top (required)>'
        from C:/Ruby23-x64/bin/dryrun:22:in `load'
        from C:/Ruby23-x64/bin/dryrun:22:in `<main>'
```

**Comment by cesarferreira** [comment]
I just fixed the bug, it happened because the project has an invalid/missing `settings.gradle` file. The fix will be in the `0.7.10` version
