### ISSUE TITLE
adb not found

### ISSUE THREAD

**Issue by xjh1994** [cesarferreira/dryrun#58]
``` 
.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - /platform-tools/adb (Errno::ENOENT)
	from /Users/xjh1994/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /Users/xjh1994/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from /Users/xjh1994/.rvm/gems/ruby-2.3.0/gems/dryrun-0.8.0/lib/dryrun/dryrun_utils.rb:50:in `run'
	from /Users/xjh1994/.rvm/gems/ruby-2.3.0/gems/dryrun-0.8.0/lib/dryrun/dryrun_utils.rb:46:in `run_adb'
	from /Users/xjh1994/.rvm/gems/ruby-2.3.0/gems/dryrun-0.8.0/lib/dryrun.rb:108:in `pick_device'
	from /Users/xjh1994/.rvm/gems/ruby-2.3.0/gems/dryrun-0.8.0/lib/dryrun.rb:171:in `call'
	from /Users/xjh1994/.rvm/gems/ruby-2.3.0/gems/dryrun-0.8.0/bin/dryrun:5:in `<top (required)>'
	from /Users/xjh1994/.rvm/gems/ruby-2.3.0/bin/dryrun:23:in `load'
	from /Users/xjh1994/.rvm/gems/ruby-2.3.0/bin/dryrun:23:in `<main>'
	from /Users/xjh1994/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xjh1994/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by xjh1994** [comment]
And I have already put `adb` in my `PATH`

**Comment by snowjade** [comment]
![image](https://cloud.githubusercontent.com/assets/11959369/20126164/f007840a-a66d-11e6-85d0-66f40b0803fe.png)

**Comment by xjh1994** [comment]
@snowjade GREAT! Problem Solved! Thanks! I have thought about this, but i just put xxx/platform-tools in PATH.
