### ISSUE TITLE
Option to run dryrun on a folder instead of a remote URL

### ISSUE THREAD

**Issue by cesarferreira** [cesarferreira/dryrun#74]
```bash
dryrun ~/code/android-hello-world
```

**Comment by wxmylife** [comment]
use ‘dryrun https://github.com/alorma/TimelineView',
an error : 
`Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:160)
	at org.gradle.wrapper.Install.access$400(Install.java:29)
	at org.gradle.wrapper.Install$1.call(Install.java:70)
	at org.gradle.wrapper.Install$1.call(Install.java:47)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	... 3 more
`

  Something went wrong while executing this:
  $ ./gradlew clean

**Comment by ftc300** [comment]
@cesarferreira ![image](https://cloud.githubusercontent.com/assets/12816061/20995482/5a6b4aa4-bd32-11e6-8559-ed71f8243e56.png)

**Comment by cesarferreira** [comment]
@ftc300 this is an issue labeled `enhancement`, this feature is not implemented yet

**Comment by ftc300** [comment]
Thanks,sir.I have known the mean of label and I'm looking forward to the enhancement.
