### ISSUE TITLE
Getting  Something went wrong while executing this:   $ ./gradlew clean issue

### ISSUE THREAD

**Issue by ckdevrel** [cesarferreira/dryrun#83]
I am getting this issue while i try to build apk from any git url. Please guide me

**Comment by cesarferreira** [comment]
That is not very specific, I need to read the logs, etc.

**Comment by privatez** [comment]
I got this issue too.
Here is the logs:

Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/private/.gradle/wrapper/dists/gradle-3.2-all/4rilkfbau3lq827lbghgcfk3kh/gradle-3.2-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)


======================================================

 Something went wrong while executing this:
  $ ./gradlew clean

**Comment by privatez** [comment]
i got this issue too.Just remove your local gradle files and try to install your dryrun project.

**Comment by luispereira** [comment]
As @cesarferreira told, this is very generic and is mostly by project setup fault. 

e.g. 
dryrun https://github.com/romandanylyk/PageIndicatorView

Would result in error, because the owner of the project commited bintrayv1.gradle file redirecting to the local.properties file, which does not exist. 

This happens a lot, because most people does not setup projects correctly.
